### ISSUE TITLE
Symlinks ignoring

### ISSUE THREAD

**Issue by apavelm** [vinser/flibgolite#31]
For some significant reason, I'd like to add only symlinks to **/books** directory. Unfortunately, **flibgolite** doesn't resolve them and just ignoring. It would be nice to fix this issue. The fix is simple and won't take much time/effort.
Thank you!

**Comment by apavelm** [comment]
@vinser I'm not familiar with GOLANG (otherwise I'd prepare a PR), but I hope this will help: [SO link](https://stackoverflow.com/questions/18062026/resolve-symlinks-in-go)

**Comment by vinser** [comment]
@apavelm  Yes, a symlink can be useful if the file cannot be moved, for example, when it stands on a torrent distribution. ;)
Thanks for the suggestion, I'll think about how to do it better.  But I can't promise a quick solution because I have to  be a bit busy with another branch after my vocations. Sorry

**Comment by vinser** [comment]
Links to directiries were tested and service works as usual:
**Windows 10**
mklink /J .\books D:\FGL\books
**Ubuntu 24.04**
ln -s /home/vinser/Dev/books books

> For some significant reason, I'd like to add only symlinks to /books directory. 
It is possible to copy or create book files/arcives to stock folder when the service is on.
It will wait the copying ends.
